FROM node:latest
EXPOSE 8080
WORKDIR /app
CMD npm install -g mocha && npm install chai && npm install expect && npm install request && npm install q && npm install date.js && npm install underscore && mocha ./test/test_user.js

