version: '2'

services:
 nginx:
  depends_on: [node]
  image: nginx:latest
  ports:
   #host:container
   #so map 8080 on the host to port 80 on nginx container
   #this is so that nginx will take incoming port 8080 traffic as 80 and fwd it to
   #the node container which should be listening on 8080
   - 80:80
  volumes:
   - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
 

 node:
  depends_on: [db]
  env_file:
   - dev-vars.env
  build: ./docker/node/
  expose:
   # expose 8080 on the node container
   - 8080
   - 3000
  volumes:
   - .:/app
   - ./docker/node/env.json:/app/env.json

 # test:
 #  depends_on: [node]
 #  env_file:
 #   - dev-vars.env
 #  build: ./docker/test/
 #  expose:
 #   # expose 8080 on the node container
 #   - 80
 #  volumes:
 #   - .:/app
 #   - ./docker/node/env.json:/app/env.json

 db:
  env_file:
   - dev-vars.env
  image: postgres:latest
  ports: 
   - 5432:5432
  volumes:
    - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    - ./db/data:/data/postgres
